### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by AlexTsamala** [AlexTsamala/Code-Crafters#2]
1.ამატებ მობილურის მოდალს,სადაც გამოჩნდება კითხვები დაარესტარტოს მომხმარებელმა თამაში თუ ახლიდან დაიწყოს.
2.ასევე აწყობ დეკსტოპის და ტაბლეტის მეორე ვერსიასაც.

**Comment by GiorgiJulakidze1997** [comment]
also add to closer of menu by onmousedown event. (useEffect and useRef)
